# what is the goal of your workflow
# goal: whenever someone changes the python code 
# the linter will check if the sytax,format,indentation [linting] is correct or not

name: auto linter

on:
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
    # this step will automatically clone the code of the current branch into the runner
      - name: checkout/clone the code
        uses: actions/checkout@v7
    # this step will install python with your preferd version
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
    # this step will install the linting tool
      - name: install linter
        run: pip install ruff
    # this step will run the linter
      - name: check the file for linting
        run: ruff check .
